name: skript-placeholders
main: io.github.apickledwalrus.skriptplaceholders.SkriptPlaceholders
api-version: 1.13
version: @version@
authors: [APickledWalrus, Pikachu920]
description: Allows using and registering placeholders with PlaceholderAPI in Skript.
website: https://github.com/APickledWalrus/skript-placeholders
softdepend: [Skript, PlaceholderAPI]
# Required for Folia and CanvasMC (a Folia fork). Do not use canvas-supported:
# that tag is only for plugins that depend on Canvas-specific API.
folia-supported: true
